### ISSUE TITLE
Problem pulling data from Todoist

### ISSUE THREAD

**Issue by FollowTheFez** [Ledaryy/obsidian-todoist-completed-tasks#27] opened 2023-04-08 10:44 UTC
Tested with multiple internet connections. The problem persists regardless.

![Screen Shot 2023-04-08 at 10 43 14 PM](https://user-images.githubusercontent.com/130220700/230716937-50e21c4d-434a-49bf-ac76-67b87f9353ab.png)

**Comment by terrymullett** [comment] 2023-05-18 11:47
I have this problem too, or a variation of it anyway. It came up some time last year also, and seems to be tied to particular days.. Yesterday it happened again. I couldn't fetch yesterday's tasks into the page yesterday, nor can I today, but I can fetch today's tasks today. 

I understand this might be obvious but will point out anyway... If the plugin can see that you have 4 tasks completed, then it seems it can access one Todoist API call to get that number (and presumably the IDs for the individual tasks). The fetch for an individual task's details fails.

**Comment by Ledaryy** [comment] 2023-05-27 19:55
Hi @FollowTheFez and @terrymullett 
Thanks for reporting the issue.
@terrymullett you are correct, it happens during extraction for additional information for individual tasks.
I'm closing this issue because it is a duplicate of [issue](https://github.com/Ledaryy/obsidian-todoist-completed-tasks/issues/17)

**Closed by Ledaryy** 2023-05-27 19:55 UTC
